name: Test

on: push

jobs:
  test:
    name: Test (Cucumber)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Install Godog
        run: go get github.com/cucumber/godog/cmd/godog@v0.11.0
      - name: Run BDD tests
        run: godog